name: checkpatch review
on: [pull_request]
jobs:
  my_review:
    name: checkpatch review
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run checkpatch review
      uses: ronenoch/action-checkpatch@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
